version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
  - package-ecosystem: "npm"
    directory: "/apps/admin"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/nova-orbit"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/nova-comms"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/nova-deck"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/nova-pulse"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/nova-synth"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/nova-lore"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/nova-core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/nova-shared"
    schedule:
      interval: "weekly"
