services:
  # Database
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: nova_db
      POSTGRES_USER: nova_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nova_user -d nova_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Nova Synth - API Server & Cosmo AI
  nova-synth:
    build:
      context: ./apps/nova-synth
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://nova_user:nova_password@postgres:5432/nova_db?schema=public
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./apps/nova-synth:/app
      - /app/node_modules

  # Nova Orbit - Portal App
  nova-orbit:
    build:
      context: ./apps/nova-orbit
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - nova-synth
    volumes:
      - ./apps/nova-orbit:/app
      - /app/node_modules

  # Nova Core - Admin App
  nova-core:
    build:
      context: ./apps/nova-core
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3002:3000"
    depends_on:
      - nova-synth
    volumes:
      - ./apps/nova-core:/app
      - /app/node_modules

  # Nova Pulse - Technician Workspace
  nova-pulse:
    build:
      context: ./apps/nova-pulse
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3003:3000"
    depends_on:
      - nova-synth
    volumes:
      - ./apps/nova-pulse:/app
      - /app/node_modules

  # Nova Lore - Knowledge Base
  nova-lore:
    build:
      context: ./apps/nova-lore
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3004:3000"
    depends_on:
      - nova-synth
    volumes:
      - ./apps/nova-lore:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:
