name: Documentation Issue
description: Report issues with documentation or suggest improvements
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees:
  - itristenx
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: doc-type
    attributes:
      label: What type of documentation issue is this?
      options:
        - Typo or grammar error
        - Missing information
        - Incorrect information
        - Outdated information
        - New documentation needed
        - Unclear or confusing content
        - Other
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Where is the documentation issue?
      description: Please provide the file path, URL, or specific location of the documentation issue.
      placeholder: ex. README.md, docs/installation.md, etc.
    validations:
      required: true
  - type: textarea
    id: current-content
    attributes:
      label: Current content (if applicable)
      description: Copy and paste the current content that needs to be changed.
    validations:
      required: false
  - type: textarea
    id: suggested-content
    attributes:
      label: Suggested improvement
      description: What should the content say instead? Or what new content should be added?
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the documentation issue here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true